# version: '3.5'
services:
  notifier:
    container_name: notifier
    restart: unless-stopped
    build:
      context: .
      args:
        - BASE_URL=/notifier
    image: notifier
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    volumes:
      - ./data:/notifier/data
# volumes:
#   node_modules_notifier: